opt_out_usage

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out https://docs.fastlane.tools/actions
# For a list of all available plugins, check out https://docs.fastlane.tools/plugins/available-plugins

default_platform(:android)

platform :android do

  desc "Build a new feature version"
  lane :build_feature do |options|
    bundle_release(options)
  end

  desc "Deploy a new candidate version to Google Play"
  lane :deploy_candidate do |options|
    bundle_release(options)

    options[:track] = "internal"
    upload_bundle_to_play_store(options)
  end

  desc "Deploy a new release version to Google Play"
  lane :deploy_release do |options|
    bundle_release(options)

    options[:track] = "beta"
    upload_bundle_to_play_store(options)
  end

  ################## BUILD ##################
  private_lane :bundle_release do |options|
    # check if gradle build-flags are necessary
    flags = "--refresh-dependencies"

    # for version
    if options[:major]
      flags += " -Pmajor=" + options[:major]
    end
    if options[:minor]
      flags += " -Pminor=" + options[:minor]
    end
    if options[:hotfix]
      flags += " -Photfix=" + options[:hotfix]
    end
    if options[:build]
      flags += " -Pbuild=" + options[:build]
    end

    # always clean before building
    task = "clean bundleRelease"

    gradle(
      task: task,
      flags: flags
    )
  end

  ################## UPLOAD #################
  private_lane :upload_bundle_to_play_store do |options|
    uploadOptions = {
      :track => options[:track],
      :skip_upload_apk => true,
      :skip_upload_aab => false,
      :aab => lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    }
    if !options[:ignoreMapping]
      uploadOptions[:mapping] = File.absolute_path "../app/build/outputs/mapping/release/mapping.txt"
    end
    upload_to_play_store(uploadOptions)
  end

end
